[tool.poetry]
name = "api"
version = "0.1.0"
description = "Vipere serverless"
authors = ["Oscar Bahamonde <oscar.bahamonde@hatarini.com>"]

[tool.poetry.dependencies]
python = "^3.8,<3.9"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
