// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Dark: typeof import('./components/Dark.vue')['default']
    Ico: typeof import('./components/Ico.vue')['default']
    IsDark: typeof import('./components/IsDark.vue')['default']
    Logo: typeof import('./components/Logo.vue')['default']
    Nav: typeof import('./components/Nav.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Store: typeof import('./components/Store.vue')['default']
  }
}

export {}
